name: Generate Data for DOCS

on:
  push:
    branches: ["master", "transformer"]

permissions: write-all

jobs:
  generate-data-for-docs:
    runs-on: ubuntu-latest
  build:
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm install axios algoliasearch

      - name: Run Node function and create file
        env:
          GITBOOK_API_KEY: ${{ secrets.production_GITBOOK_API_KEY }}
          ALGOLIA_APPID: ${{ secrets.production_ALGOLIA_APPID }}
          ALGOLIA_APIKEY: ${{ secrets.production_ALGOLIA_APIKEY }}
        run: node script/transformer.js

      - name: Commit changes
        run: |
          git switch -c version-branch
          git config --global user.email "test@zesty.io"
          git config --global user.name "Zesty Test"
          git add .
          git commit --allow-empty -m ":rocket: chore: bump Docs Data"
          git push origin version-branch:master
